### ISSUE TITLE
Should be 'and' instead of 'or'. Otherwise, self.language will always be 'pt' 

### ISSUE THREAD

**Issue by JasonMengcp** [vwoloszyn/pylinguistics#1]
https://github.com/vwoloszyn/pylinguistics/blob/362a883b0fcf07c583a8fbd3f2d1a87a3645fc5e/pylinguistics/Pylinguistics.py#L64

**Comment by Suya** [comment]
Thanks for noting this issue, we will fix this as soon as it's convenient.
