### ISSUE TITLE
import and tools error

### ISSUE THREAD

**Issue by ScArEcRoW2112** [vwoloszyn/pylinguistics#6]
Hi, I was trying to import the Pylinguistics module and it returns an error:

File "C:\Users\ScArEcRoW\AppData\Local\Programs\Python\Python39\Lib\site-packages\pylinguistics-master\./pylinguistics\tools.py", line 114
    print pylinguistObj.language
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(pylinguistObj.language)?

I'm executing this inside the pylinguistics-master folder, if I execute this outside, it returns this: 

File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Pylinguistics

I already installed the setup.py. Python version 3.9.3

**Comment by Suya** [comment]
Ok, the issue is that the code is in python 2, which doesn't require
parenthesis. It is somewhat simple to upgrade the code to python 3 if you
want, just follow the exceptions.

I hope in doing that someday but right now i'm too involved in a current
project.

Good luck!
